x-common: &common
  restart: unless-stopped
  networks:
    - wordpress-network

networks:
  wordpress-network:
    driver: bridge

services:
  db:
    <<: *common
    image: mariadb:10.11
    container_name: db-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_buffer_pool_size=${DB_MEMORY_LIMIT:-1G}
      - --innodb_log_file_size=256M
      - --max_connections=${DB_MAX_CONNECTIONS:-100}
    deploy:
      resources:
        limits:
          memory: ${DB_MEMORY_LIMIT}
          cpus: ${DB_CPU_LIMIT}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      timeout: 20s
      retries: 10

  wordpress:
    <<: *common
    image: wordpress:php8.3-fpm
    container_name: wordpress
    user: "1000:1000"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      PHP_OPCACHE_ENABLE: ${PHP_OPCACHE_ENABLE}
      PHP_OPCACHE_MEMORY_CONSUMPTION: ${PHP_OPCACHE_MEMORY_CONSUMPTION}
      PHP_OPCACHE_MAX_ACCELERATED_FILES: ${PHP_OPCACHE_MAX_ACCELERATED_FILES}
    volumes:
      - wordpress_data:/var/www/html
    deploy:
      resources:
        limits:
          memory: ${WP_MEMORY_LIMIT_STATIC}
          cpus: ${WP_CPU_LIMIT_STATIC}
    depends_on:
      db:
        condition: service_healthy

  angie:
    <<: *common
    build:
      context: .
      dockerfile: Dockerfile.angie.unroot
    image: my-angie:1.9.1-ubuntu
    container_name: web-angie
    ports:
      - "${ANGIE_PORT:-80}:80"
    volumes:
      - ./src/config/angie/angie.conf:/etc/angie/angie.conf
      - ./src/config/angie/main-${ENVIRONMENT}.conf:/etc/angie/http.d/main.conf
      - wordpress_data:/var/www/html:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: ${ANGIE_MEMORY_LIMIT}
          cpus: ${ANGIE_CPU_LIMIT}
    depends_on:
      - wordpress

volumes:
  mariadb_data:
    name: ${COMPOSE_PROJECT_NAME}_mariadb_data
  wordpress_data:
    name: ${COMPOSE_PROJECT_NAME}_wp_data